10.DatatablesView/config/urls.py
from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
    path('', include('sample.urls')),
    path('todo/', include('todo.urls')),
]

# イタズラ防止のため管理画面は開発環境のみで有効とします。
if settings.DEBUG:
    urlpatterns += [path('admin/', admin.site.urls)]

10.DatatablesView/sample/urls.py
from django.urls import path
from django.views.generic.base import TemplateView

from . import views

app_name = 'sample'

urlpatterns = [
    path('', TemplateView.as_view(template_name='sample/index.html'), name='index'),
    path('sample01', TemplateView.as_view(template_name='sample/sample01.html'), name='sample01'),
    path('sample02', TemplateView.as_view(template_name='sample/sample02.html'), name='sample02'),
    path('items', views.ItemsJsonView.as_view(), name='ItemsJson'),
    path('print', views.PrintView.as_view(), name='print'),
    path('excel', views.ExcelView.as_view(), name='excel'),
    path('csv', views.CsvView.as_view(), name='csv'),
]

10.DatatablesView/todo/urls.py
from django.urls import path, include
from rest_framework import routers

from . import views
from .views import TaskViewSet

router = routers.DefaultRouter()
router.register(r'tasks', TaskViewSet)

app_name = 'todo'

urlpatterns = [
    path('', views.MainView.as_view(), name='index'),
    path('api/datatables', views.TasksJsonView.as_view(), name='TasksJson'),
    path('api/', include(router.urls)),
]

10.DatatablesView/sample/models.py
from django.db import models


# Create your models here.
class Item(models.Model):
    # 県名
    pref_name = models.CharField(
        verbose_name='県名',
        max_length=4,
    )

    # 市町村名
    name = models.CharField(
        verbose_name='市町村名',
        max_length=15,
    )

    # ふりがな
    furigana = models.CharField(
        verbose_name='ふりがな',
        max_length=30,
    )

    # 郵便番号
    zipcode = models.CharField(
        verbose_name='郵便番号',
        max_length=8,
    )

    # 住所
    address = models.CharField(
        verbose_name='住所',
        max_length=100,
    )

    # 電話番号
    tel = models.CharField(
        verbose_name='電話番号',
        max_length=13,
    )

    # 自治体コード
    code = models.CharField(
        verbose_name='自治体コード',
        max_length=6,
    )

    def __str__(self):
        """
        リストボックスや管理画面での表示
        """
        return self.name

    class Meta:
        """
        管理画面でのタイトル表示
        """
        verbose_name = '自治体データ'
        verbose_name_plural = '自治体データ'

10.DatatablesView/todo/models.py
from django.db import models


# Create your models here.
class Task(models.Model):
    # タイトル
    title = models.CharField(
        verbose_name='タイトル',
        max_length=100,
    )

    # 詳細
    detail = models.TextField(
        verbose_name='詳細',
        blank=True,
        null=True,
        max_length=1000,
    )

    # ステータス値
    # status_choice = (
    #     (0, '未着手'),
    #     (1, '対応中'),
    #     (2, '完了'),
    # )

    # ステータス
    status = models.IntegerField(
        verbose_name='ステータス',
        # choices=status_choice,
        default=0,
    )

    # 論理削除フラグ
    is_deleted = models.BooleanField(
        verbose_name='削除済み',
        default=False,
    )

    created_at = models.DateTimeField(
        verbose_name='登録時間',
        blank=True,
        null=True,
        auto_now_add=True,
    )

    updated_at = models.DateTimeField(
        verbose_name='登録時間',
        blank=True,
        null=True,
        auto_now=True,
    )

    def __str__(self):
        """
        リストボックスや管理画面での表示
        """
        return self.title

    class Meta:
        """
        管理画面でのタイトル表示
        """
        verbose_name = 'ToDoタスク'
        verbose_name_plural = 'ToDoタスク'

10.DatatablesView/todo/forms.py
from django import forms

from .models import Task


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ('title', 'detail')
        # widgets = {
        #     'detail': forms.Textarea(attrs={'rows': 4}),
        # }

10.DatatablesView/sample/views.py
from django.views import generic
from django_datatables_view.base_datatable_view import BaseDatatableView
from excel_response import ExcelMixin

from .models import Item


# DataTablesにデータを提供するWebAPI
# django-datatables-view
# https://pypi.org/project/django-datatables-view/
class ItemsJsonView(BaseDatatableView):
    # モデルの指定
    model = Item
    # フィールドの指定
    columns = ['id', 'pref_name', 'name', 'furigana', 'zipcode', 'address', 'tel', 'code']

    # 検索方法の指定：部分一致
    def get_filter_method(self):
        return super().FILTER_ICONTAINS


# 印刷・Excel・CSV出力の基底クラス
class BaseReportView(generic.ListView):
    model = Item

    # 選択データの取得
    def get_queryset(self):
        id_list = self.request.GET['id_list'].split('_')
        result = Item.objects.filter(id__in=id_list)
        return result


# 印刷画面表示
class PrintView(BaseReportView):
    template_name = 'sample/print.html'


# Excelダウンロード
# django-excel-response
# https://pypi.org/project/django-excel-response/
class ExcelView(ExcelMixin, BaseReportView):

    # 見出し行を日本語にする
    def get_queryset(self):
        header = [['id', '県名', '市町村名', 'ふりがな', '郵便番号', '住所', '電話番号', '自治体コード']]
        body = [list(entry.values()) for entry in super().get_queryset().values()]
        return header + body


# CSVダウンロード
class CsvView(ExcelView):
    force_csv = True

10.DatatablesView/todo/views.py
# Create your views here.
from django.views.generic import FormView
from django_datatables_view.base_datatable_view import BaseDatatableView
from rest_framework import serializers
from rest_framework import viewsets

from .models import Task
from .forms import TaskForm

class MainView(FormView):
    template_name = 'todo/index.html'
    form_class = TaskForm


class TasksJsonView(BaseDatatableView):
    # モデルの指定
    model = Task
    # フィールドの指定
    columns = ['id', 'status', 'title', 'detail', 'created_at', 'updated_at']

    # 検索方法の指定：部分一致
    def get_filter_method(self):
        return super().FILTER_ICONTAINS

    def get_initial_queryset(self):
        return Task.objects.filter(is_deleted=False)


class TaskSerializer(serializers.ModelSerializer):
    class Meta:
        model = Task
        fields = '__all__'


class TaskViewSet(viewsets.ModelViewSet):
    queryset = Task.objects.all()
    serializer_class = TaskSerializer

10.DatatablesView/sample/templates/sample/index.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Django-Datatables-View サンプル</title>
</head>
<body>
<h3>Django-Datatables-View サンプル</h3>
<ul>
    <li><a href="{% url 'sample:sample01' %}">サンプル１：ＰＣ用</a></li>
    <div>チェックボックスによる行の選択。Excel出力, CSV出力, 印刷機能。</div>
    <li><a href="{% url 'sample:sample02' %}">サンプル２：モバイル用</a></li>
    <div>レスポンシブ対応。</div>
    <li><a href="{% url 'todo:index' %}">サンプル３：タスク管理ツール</a></li>
    <div>データ編集画面を追加したサンプルアプリ</div>
</ul>
</body>
</html>

10.DatatablesView/sample/templates/sample/print.html
{% load static %}

{#/* HTML帳票の開発は以下のリンクを参照 */#}
{##}
{#/* Qiita:そろそろ真面目に、HTMLで帳票を描く話をしようか */#}
{#/* https://qiita.com/cognitom/items/d39d5f19054c8c8fd592 */#}
{#/* Qiita:紙の帳票からHTML帳票を作る方法 */#}
{#/* https://qiita.com/okoppe8/items/45e7b37774899e763d31 */#}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>印刷画面</title>
    <link href="{% static "sample/css/print.css" %}" rel="stylesheet">
</head>
<body class="A4">
<section class="sheet">
<div class="flex">

{% for item in object_list  %}
<div class="cell">
<p class="zipcode">{{ item.zipcode }}</p>
<p class="pref_name">{{ item.pref_name }}</p>
<p class="address">{{ item.address }}</p>
<p class="name">{{ item.name }} 御中</p>
</div>
{# 用紙1枚毎に単票が12枚 #}
{% if forloop.counter|divisibleby:"12" and not forloop.last %}
</div>
</section>
<section class="sheet">
<div class="flex">
{% endif %}

{% endfor %}
</div>
</section>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script type="text/javascript">

    $(document).ready(function () {
        // 印刷画面を自動的に表示。印刷実行かキャンセルでウィンドウも閉じる。
        setTimeout(function () {
            window.print();
            window.close();
        }, 200);
    })

</script>
</body>
</html>

10.DatatablesView/sample/templates/sample/sample01.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

<head>
    <!-- Required meta tags always come first -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>地方自治体一覧</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.1/css/bootstrap.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/select/1.2.7/css/select.dataTables.min.css" rel="stylesheet">
</head>

<nav class="navbar navbar-expand-md navbar-light bg-light mb-3">
    <a class="navbar-brand" href="#">地方自治体一覧</a>
    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#Navber" aria-controls="Navber"
            aria-expanded="false"
            aria-label="ナビゲーションの切替">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="Navber">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="/">トップにもどる</a>
            </li>
        </ul>
    </div>
</nav>

<div class="container">
    <div class="row">
        <div class="col-12">
            <table id="datatable" class="table table-striped table-bordered nowrap" cellspacing="0"
                   width="100%"></table>
        </div>
    </div>
    <div class="mt-3 mb-3">
        <div>選択中のデータ：<span id="selected"></span></div>
        <button id="clear" type="button" class="btn-lg btn-secondary mr-3">選択を解除</button>
        <button id="print" type="button" class="btn-lg btn-primary report">印刷</button>
        <button id="excel" type="button" class="btn-lg btn-primary report">Excel</button>
        <button id="csv" type="button" class="btn-lg btn-primary report">CSV</button>
    </div>
</div>
<form id="form">
    <input type="hidden" name="id_list">
</form>

<!-- jQuery first, then Tether, then Bootstrap JS. -->
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
<script src="{% static "sample/js/sample.js" %}"></script>

</body>

</html>

10.DatatablesView/sample/templates/sample/sample02.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

<head>
    <!-- Required meta tags always come first -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>地方自治体一覧</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.1/css/bootstrap.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/responsive/2.2.3/css/responsive.bootstrap4.min.css" rel="stylesheet">
    <style>
    /* 詳細を広げたときに文字列が画面をはみ出さないようにする */
    span.dtr-data {
        white-space: normal;
    }
    </style>
</head>

<nav class="navbar navbar-expand-md navbar-light bg-light mb-3">
    <a class="navbar-brand" href="#">地方自治体一覧</a>
    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#Navber" aria-controls="Navber"
            aria-expanded="false"
            aria-label="ナビゲーションの切替">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="Navber">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="/">トップにもどる</a>
            </li>
        </ul>
    </div>
</nav>

<div class="container">
    <div class="row">
        <div class="col-12">
            <table id="datatable" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0"
                   width="100%"></table>
        </div>
    </div>
</div>
<form id="form">
    <input type="hidden" name="id_list">
</form>

<!-- jQuery first, then Tether, then Bootstrap JS. -->
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.2.3/js/responsive.bootstrap4.min.js"></script>
<script src="{% static "sample/js/sample.js" %}"></script>

</body>

</html>